bin/magento setup:install \
--base-url=http://m242os.mg.loc \
--db-host=localhost \
--db-name=m242os \
--db-user=nofarius \
--db-password=nofariusamdm \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1
